apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mern-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/alielhamadi/k8s-manifests.git
    targetRevision: main
    path: k8s-manifests   # ✅ IMPORTANT

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true