apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: elhamadiinnovator/appagrogitops-backend:v6
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          # AJOUTEZ CETTE SECTION :
          env:
            - name: MONGO_URI
              value: "mongodb://mongo-service:27017/employes_db"
            - name: PORT
              value: "9000"
            - name: NODE_ENV
              value: "development"